name: mobile_flutter
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  # Versão recomendada para o SDK Dart
  sdk: ^3.0.0 

# A SEÇÃO DE DEPENDÊNCIAS DEVE FICAR APENAS AQUI!
dependencies:
  # O Flutter SDK deve ser o primeiro item na lista de dependências
  flutter:
    sdk: flutter

  # Dependências Adicionadas para o Projeto (CRUD Mobile)
  http: ^1.1.0 # Versão atualizada e estável para requisições HTTP
  shared_preferences: ^2.2.2 # Versão atualizada
  provider: ^6.1.1 # Versão atualizada
  intl: ^0.19.0 # Versão atualizada
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # Versão atualizada

flutter:
  uses-material-design: true

  # Aqui ficariam assets e fontes, mas não a chave 'dependencies'